from collections import deque
q = deque()
q.append(10)
q.append(20)
q.append(30)
q.append(40)
print("intial queue is = ",q)
print(q.popleft())
print(q.popleft())
print("After removing element = ",q)
q.append(20)
q.append(30)
q.append(40)
print("After removing element = ",q)
print(q.popleft())